disabled_rules:
  - line_length
  - trailing_whitespace
  - todo
  - variable_name_min_length
  - function_body_length
  - cyclomatic_complexity
  - variable_name
  - type_name
  - file_length
included: # paths to include during linting. `--path` is ignored if present.
  - Today iOS App
  - Today Watch App
  - TodayKit Shared Code
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
